# Generated by Django 4.0.7 on 2022-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(blank=True, upload_to="resources/"),
        ),
        migrations.AddField(
            model_name="resource",
            name="image_link",
            field=models.URLField(blank=True),
        ),
    ]
