# Generated by Django 4.0.7 on 2022-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0005_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="sub_title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
