# Generated by Django 4.0.7 on 2022-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("author", models.TextField(blank=True, default="unknown")),
                ("pages", models.PositiveIntegerField(blank=True)),
                ("cover", models.ImageField(blank=True, upload_to="documents/")),
            ],
        ),
    ]
